# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

target 'DouYu' do


 pod 'Alamofire', '~> 4.0.0'
 pod 'Kingfisher', '~> 3.0.1'

end
